#!/usr/bin/env bash
set -e

source ./version.sh

export NVM_DIR=$HOME/.nvm

if [[ ! -d $NVM_DIR ]]; then
  mkdir -p $NVM_DIR
  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
fi

if [[ ! $(command -v nvm) ]]; then
  set +e
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
  set -e
fi

#nvm install

if [[ ! $(command -v yarn) ]]; then
    npm install -g yarn
fi

yarn install

dist=build/artifacts/dist
out=build/artifacts/out

yarn clean
yarn build
yarn test

function package() {
    if [[ ! $(command -v envsubst) ]]; then
        sudo apt-get install gettext
    fi

    mkdir -p ${dist}
    envsubst < package.json > ${dist}/package.json
    cp -r src/* ${dist}
    cp -r ${out}/src/* ${dist}
    cp README.md LICENSE ${dist}
}

function publish() {
    mkdir -p ${dist}
    cat >${dist}/.npmrc <<EOL
@bodar:registry=https://registry.npmjs.org
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
EOL
    pushd ${dist}
    npm publish --tag ${TAG} --access public
    popd
}

function ci() {
    package
    publish
}

if [[ -n "$1" ]]; then
    "$1"
fi
