#!/usr/bin/env bash
set -Eeo pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
export NPM_TOKEN=${NPM_TOKEN-}

source ${dir}/nvm.sh

if [[ ! $(command -v pnpm) ]]; then
    npm install -g pnpm
fi

source ${dir}/version.sh

function build() {
  pnpm install --no-frozen-lockfile # Can't get CI to build without it even when lock file in sync
  pnpm circular -r --if-present
  pnpm exec tsc --build --force
  pnpm test -r --filter=*test
}

function ci() {
  build
  pnpm publish -r --filter=!*test --no-git-checks --tag ${TAG}
}

command="${1-build}"
set +e; shift; set -Eeo pipefail;
$command "$@"